services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: stock_postgres
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      #2/20/2026 just changed from ' - "5432:5432"'  to:
      - "${POSTGRES_PORT:-5432}:5432" #allows for overrides, but defaults to 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/init:/docker-entrypoint-initdb.d:ro # <-- init SQL files run on first start
    #- ${KAGGLE_CONFIG}:/root/.kaggle:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stock_user -d stock_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Backend.Dockerfile
    container_name: stock_backend
    environment:
      DATABASE_URL: postgresql://stock_user:stock_pass@postgres:5432/stock_db
      INPUT_JSON: /app/data/reliance_news.json
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: stock_db
      PG_USER: stock_user
      PG_PASS: stock_pass
      KAGGLE_CONFIG_DIR: /root/.kaggle
      NEWS_CSV_PATH: /app/data/reliance_news_sentiment.csv
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./Testing:/app/Testing
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  # Frontend React App (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Frontend.Dockerfile
    container_name: stock_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped

volumes:
  postgres_data:
