import "./FunFinanceFacts.css";

const FACTS: string[] = [
  "The S&P 500 has returned an average of approximately 10 percent annually since 1957, before adjusting for inflation.",
  "Warren Buffett earned over 99 percent of his net worth after his 50th birthday, illustrating the power of compound growth over time.",
  "The New York Stock Exchange was founded in 1792 under a buttonwood tree on Wall Street.",
  "A 50 percent loss requires a 100 percent gain just to return to the original value, which is why limiting downside matters.",
  "Studies consistently show that roughly 90 percent of active day traders lose money over the long term.",
  "Index funds now account for more US stock assets than actively managed funds, a milestone crossed in 2019.",
  "Stock market corrections, defined as drops of 10 percent or more from a recent high, occur on average once per year historically.",
  "Diversification reduces portfolio risk without reducing expected returns, which is why economists call it the only free lunch in investing.",
  "Amazon's IPO price in 1997 was $18 per share. Adjusted for all stock splits, that equals less than $1.50 per share in today's terms.",
  "Compound interest was once described as the eighth wonder of the world, though economists debate the exact attribution.",
  "Dollar-cost averaging involves investing a fixed amount on a regular schedule, removing the pressure of timing the market perfectly.",
  "Stocks have outperformed bonds in every 30-year period in recorded US market history.",
  "The US stock market represents approximately 42 percent of total global market capitalization.",
  "Missing only the 10 best trading days in each decade can cut long-term returns roughly in half.",
  "Peter Lynch averaged 29.2 percent annual returns managing the Fidelity Magellan Fund from 1977 to 1990.",
  "The Dow Jones Industrial Average was first published on May 26, 1896, with a starting value of 40.94.",
  "A portfolio earning 7 percent annually doubles in value approximately every 10 years, according to the Rule of 72.",
  "The Rule of 72 is a mental formula: divide 72 by an annual return rate to estimate how many years it takes to double an investment.",
  "At 3 percent annual inflation, $100 today will have the purchasing power of roughly $74 in just 10 years.",
  "A bear market is defined as a decline of 20 percent or more in a major index from its most recent peak.",
  "A bull market is a period of sustained price increases, generally 20 percent or more above a recent low.",
  "US Treasury bonds are backed by the full faith and credit of the federal government, making them among the lowest-risk investments available.",
  "High-yield bonds offer higher interest rates in exchange for a greater risk that the borrower will default on payments.",
  "The price-to-earnings ratio compares a stock's share price to its earnings per share and is one of the most widely used valuation measures.",
  "A price-to-earnings ratio above 25 is often considered expensive by historical standards, while a ratio below 15 may signal potential value.",
  "Market capitalization equals a company's share price multiplied by the total number of shares outstanding.",
  "Small-cap stocks have historically outperformed large-cap stocks over long periods, but with considerably more volatility.",
  "Value investing, pioneered by Benjamin Graham, focuses on buying stocks trading below their estimated intrinsic value.",
  "Growth investing focuses on companies expected to grow faster than the broader market, often requiring investors to pay a premium price.",
  "Exchange-traded funds trade on exchanges throughout the day, unlike mutual funds, which settle at a single end-of-day price.",
  "The first US ETF, the SPDR S&P 500 ETF (ticker: SPY), launched in January 1993 and remains one of the most traded securities in the world.",
  "Expense ratios for actively managed mutual funds average around 0.66 percent per year, while index ETFs can charge as little as 0.03 percent.",
  "Over 30 years, a 1 percent annual fee difference on a $100,000 investment can cost more than $100,000 in lost returns due to compounding.",
  "Asset allocation, the division of a portfolio among stocks, bonds, and cash, is considered the primary driver of long-term investment returns.",
  "Research suggests that asset allocation decisions account for more than 90 percent of the variation in portfolio returns over time.",
  "Rebalancing a portfolio means periodically returning it to its target allocation by selling assets that have grown and buying those that have declined.",
  "Tax-loss harvesting involves selling investments at a loss to offset capital gains taxes owed on profitable sales elsewhere in the portfolio.",
  "A Roth IRA allows investments to grow tax-free, and qualified withdrawals in retirement are also tax-free.",
  "A traditional IRA offers a tax deduction on contributions, but withdrawals in retirement are taxed as ordinary income.",
  "The 401(k) contribution limit in 2025 is $23,500 for individuals under 50, with an additional $7,500 allowed for those 50 and older.",
  "Financial advisors generally recommend maintaining an emergency fund covering three to six months of expenses before investing in stocks.",
  "Liquidity describes how quickly an asset can be converted to cash without significantly affecting its price. Stocks are more liquid than real estate.",
  "Market liquidity tends to decline during periods of financial stress, which can amplify price swings in both directions.",
  "The efficient market hypothesis holds that stock prices already reflect all publicly available information, making it very difficult to consistently beat the market.",
  "Behavioral finance studies how psychological biases affect investor decisions. Overconfidence and loss aversion are among the most widely documented.",
  "Loss aversion refers to the tendency to feel losses about twice as intensely as equivalent gains, a core finding of behavioral economics.",
  "Anchoring bias causes investors to rely too heavily on the first piece of information they encounter, such as a stock's 52-week high.",
  "Recency bias leads investors to overweight recent events, which often results in buying near peaks and selling near troughs.",
  "The January Effect refers to the historical tendency for small-cap stocks to outperform in January, though the pattern has weakened in recent decades.",
  "Earnings per share is a company's net income divided by the number of outstanding shares and is a core measure of profitability per investor.",
  "Revenue is the total income a company generates from sales. Profit is what remains after subtracting all costs from that revenue.",
  "Free cash flow measures the cash a company generates after capital expenditures and is often considered a cleaner profitability measure than reported earnings.",
  "EBITDA stands for earnings before interest, taxes, depreciation, and amortization and is used to compare profitability across companies and industries.",
  "Dividends are payments made by companies to shareholders from profits, typically on a quarterly schedule.",
  "A dividend yield is calculated by dividing the annual dividend per share by the current stock price and expressing the result as a percentage.",
  "A very high dividend yield can sometimes signal financial distress, because share prices often fall faster than dividends are cut.",
  "Dividend reinvestment plans automatically use dividends to purchase additional shares, accelerating the compounding effect over time.",
  "Share buybacks reduce the total number of shares outstanding, which typically increases the value of each remaining share.",
  "The Nasdaq Composite is heavily weighted toward technology companies and is widely used as a benchmark for the tech sector.",
  "The Russell 2000 index tracks 2,000 small-cap US companies and is commonly used to gauge the health of smaller domestic businesses.",
  "Bond prices and interest rates move in opposite directions. When rates rise, existing bond prices fall; when rates fall, bond prices rise.",
  "Duration measures a bond's sensitivity to interest rate changes. A bond with a duration of 5 loses approximately 5 percent in price if rates rise 1 percent.",
  "The yield curve plots interest rates on bonds of similar credit quality across different maturities and is a closely watched economic indicator.",
  "An inverted yield curve, where short-term rates exceed long-term rates, has preceded every US recession since World War II.",
  "The Federal Reserve controls short-term interest rates through its federal funds rate target, influencing borrowing costs across the broader economy.",
  "Quantitative easing is a central bank policy of purchasing financial assets to inject money into the economy and reduce long-term interest rates.",
  "Treasury Inflation-Protected Securities automatically adjust their principal value in line with changes in the Consumer Price Index.",
  "The Consumer Price Index measures the average change in prices paid by consumers for a standardized basket of goods and services.",
  "Core inflation excludes food and energy prices, which are volatile, to provide a clearer view of underlying price trends.",
  "The Federal Reserve targets average annual inflation of 2 percent as part of its dual mandate of price stability and maximum employment.",
  "Gold has been used as a store of value for thousands of years and is often purchased as a hedge against inflation and currency weakness.",
  "Unlike stocks, gold generates no dividends or interest. Its total return depends entirely on price appreciation.",
  "Real estate investment trusts allow individual investors to access income-producing real estate without owning property directly.",
  "Real estate investment trusts are required by law to distribute at least 90 percent of their taxable income to shareholders annually.",
  "Commodities such as oil, natural gas, wheat, and copper are raw materials whose prices are driven by global supply and demand forces.",
  "Oil prices affect transportation costs, manufacturing expenses, and energy bills, shaping inflation and broader economic conditions.",
  "Cryptocurrency is a decentralized digital currency that uses cryptography for security and operates outside the control of any central bank.",
  "Bitcoin, launched in 2009, was the first cryptocurrency. Its total supply is permanently capped at 21 million coins by its underlying code.",
  "Blockchain is a distributed ledger technology that records transactions transparently and in a way that is extremely difficult to alter retroactively.",
  "Initial public offerings occur when a private company sells shares to the public for the first time on a recognized stock exchange.",
  "Most IPOs are priced below the expected market value to generate early investor demand, which typically results in a first-day price jump.",
  "The lockup period following an IPO, usually 90 to 180 days, prevents company insiders from selling their shares immediately after the offering.",
  "Short selling involves borrowing shares, selling them at the current price, and aiming to repurchase them later at a lower price.",
  "Short sellers face theoretically unlimited losses because a stock's price can rise without limit, unlike a long investor whose maximum loss is fixed.",
  "Options contracts give buyers the right, but not the obligation, to buy or sell a stock at a specified price before a set expiration date.",
  "A call option gains value when the underlying stock rises above the strike price. A put option gains value when the stock falls below it.",
  "The Black-Scholes model, developed in 1973 and recognized with the Nobel Prize in Economics, is a formula widely used to price options contracts.",
  "Derivatives are financial contracts whose value depends on an underlying asset such as a stock, bond, commodity, or currency.",
  "Leverage allows investors to control a larger position than their actual capital, amplifying both potential gains and potential losses.",
  "Margin accounts allow investors to borrow money from a brokerage to purchase securities, using the securities themselves as collateral.",
  "If assets in a margin account fall below the required minimum, the broker issues a margin call requiring more funds or forced liquidation.",
  "The Securities and Exchange Commission is the US agency responsible for regulating securities markets and protecting investors from fraud.",
  "Insider trading means buying or selling securities based on material information that has not yet been made public and is illegal in most countries.",
  "Market makers continuously quote buy and sell prices for securities, ensuring that markets remain liquid and that investors can transact efficiently.",
  "The bid-ask spread is the difference between the highest price a buyer will pay and the lowest a seller will accept. Tighter spreads indicate greater liquidity.",
  "Algorithmic trading uses computer programs to execute orders based on predefined rules and now accounts for a majority of daily stock market volume.",
  "High-frequency trading executes thousands of transactions per second and profits from tiny price discrepancies across markets and exchanges.",
  "Dark pools are private trading venues where large institutional orders execute away from public exchanges to reduce their impact on market prices.",
  "The Volcker Rule restricts US banks from making speculative investments using depositor funds, a safeguard introduced after the 2008 financial crisis.",
  "The Glass-Steagall Act of 1933 separated commercial and investment banking in the United States. It was largely repealed by the Gramm-Leach-Bliley Act in 1999.",
  "The 2008 financial crisis was triggered largely by the collapse of the US housing market and the subsequent failure of mortgage-backed securities.",
  "Lehman Brothers, founded in 1847, filed for bankruptcy on September 15, 2008, the largest such filing in US history at that time.",
  "A stock's 52-week high and low are widely referenced points that investors use to assess relative value and recent price momentum.",
  "Trading volume measures the number of shares exchanged during a given period. Unusual volume often signals an important change in market sentiment.",
  "Beta measures a stock's volatility relative to the market. A beta of 1.5 means the stock tends to move 50 percent more than the market in either direction.",
  "Alpha measures the excess return of an investment relative to its benchmark after adjusting for risk. Consistent positive alpha is extremely rare.",
  "The Sharpe ratio measures risk-adjusted return by dividing the excess return above the risk-free rate by the portfolio's standard deviation.",
  "Standard deviation measures how much returns fluctuate around their average. A higher value indicates greater uncertainty and investment risk.",
  "Correlation ranges from -1 to +1. Combining assets with low correlation provides better diversification and a smoother return profile.",
  "Modern Portfolio Theory, developed by Harry Markowitz in 1952, demonstrates mathematically how mixing low-correlation assets reduces overall portfolio risk.",
  "The efficient frontier is the set of portfolios offering the highest expected return for each level of risk, as defined by Modern Portfolio Theory.",
  "Passive investing through index funds consistently outperforms the majority of actively managed funds over periods of 10 years or more.",
  "According to SPIVA research, more than 80 percent of actively managed large-cap US funds underperform the S&P 500 over a 20-year period.",
  "The price-to-book ratio compares a company's market value to its accounting book value and is a common tool in value investing analysis.",
  "A price-to-book ratio below 1 may suggest a company is undervalued, though it can also reflect genuine financial trouble.",
  "The current ratio, calculated as current assets divided by current liabilities, measures whether a company can meet its short-term financial obligations.",
  "A current ratio below 1 suggests difficulty paying near-term debts, while a ratio above 2 may indicate assets are not being deployed efficiently.",
  "The debt-to-equity ratio compares total debt to shareholder equity, indicating how much leverage a company uses to fund its operations.",
  "Capital gains are profits earned when an investment is sold for more than its purchase price. Short-term gains are taxed at ordinary income rates.",
  "Long-term capital gains, on assets held more than one year, are taxed at preferential rates of 0, 15, or 20 percent depending on taxable income.",
  "Tax-advantaged accounts such as IRAs and 401(k) plans allow investments to compound without annual taxation, greatly improving long-term outcomes.",
  "The time value of money states that a dollar received today is worth more than a dollar received later because it can be invested and earn returns.",
  "Net present value calculates what future cash flows are worth in today's dollars, helping determine whether an investment is worth pursuing.",
  "Internal rate of return is the discount rate at which an investment's net present value equals zero. It helps compare the attractiveness of different opportunities.",
  "Opportunity cost is the value of the best alternative given up when making any financial decision. Every choice involves a trade-off.",
  "A zero-sum game is one where gains by one party are exactly offset by losses by another. Options and futures contracts are examples.",
  "Mutual funds pool money from many investors to buy a diversified portfolio of stocks, bonds, or other securities managed by a professional team.",
  "Unlike ETFs, mutual fund shares are priced once per day after the market closes, and all buy or sell orders execute at that end-of-day price.",
  "Money market funds invest in short-term, high-quality debt instruments and are designed to maintain a stable net asset value of $1 per share.",
  "Certificates of deposit pay a fixed interest rate in exchange for leaving money with a bank untouched for a predetermined period.",
  "The Federal Deposit Insurance Corporation insures bank deposits up to $250,000 per depositor per institution against bank failure.",
  "Socially responsible investing incorporates environmental, social, and governance criteria alongside financial analysis to guide investment selections.",
  "ESG investing evaluates companies on their environmental practices, social responsibility, and quality of corporate governance.",
  "Financial literacy, the ability to understand and apply financial concepts, is consistently linked to better long-term wealth building outcomes.",
  "The median US household retirement savings for workers aged 55 to 64 is approximately $185,000, far below what most financial planners recommend.",
  "The 4 percent rule suggests retirees can withdraw 4 percent of their portfolio annually with a low probability of running out of money over 30 years.",
  "Sequence of returns risk is the danger that poor market performance early in retirement can permanently impair a portfolio's longevity.",
  "An annuity is a contract with an insurance company that provides guaranteed income payments in exchange for a lump sum or series of contributions.",
  "Term life insurance combined with separate investing typically outperforms whole life insurance as a combined protection and wealth-building strategy.",
  "The most important investment decision for most people is simply to start. Time in the market consistently outweighs any attempt to time the market.",
  "The Consumer Financial Protection Bureau was established in 2010 to protect consumers from unfair, deceptive, or abusive financial practices.",
  "Credit scores in the United States range from 300 to 850. Scores above 740 typically qualify borrowers for the most favorable loan interest rates.",
  "A FICO score is based on payment history, amounts owed, length of credit history, new credit inquiries, and the mix of credit types held.",
  "Carrying a high balance relative to available credit, known as credit utilization, can significantly lower a credit score.",
  "Paying a credit card balance in full each month eliminates all interest charges, regardless of the stated annual percentage rate.",
  "The average US credit card interest rate exceeded 20 percent annually in 2024, making carrying a balance particularly expensive.",
  "An index fund does not attempt to beat the market. It holds all or nearly all the securities in a given index to match its performance at minimal cost.",
  "Passive investing gained widespread acceptance in the 1970s after research showed most active managers fail to beat benchmarks consistently after fees.",
  "John Bogle founded Vanguard in 1974 and launched the first index mutual fund available to retail investors, fundamentally changing how Americans save.",
  "The greatest investment a person can make, according to Warren Buffett, is in their own skills and knowledge, because no one can take that away.",
];

const START = new Date("2026-04-01T00:00:00");

function getTodaysFact(): string {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const dayOffset = Math.floor((today.getTime() - START.getTime()) / (1000 * 60 * 60 * 24));
  const index = ((dayOffset % FACTS.length) + FACTS.length) % FACTS.length;
  return FACTS[index];
}

export default function FunFinanceFacts() {
  const fact = getTodaysFact();
  //Get random finance fact every day
  return (
    <div className="fff-card">
      <div className="fff-label">Finance Fact of the Day</div>
      <p className="fff-fact">{fact}</p>
      <div className="fff-footer">
        <p className="fff-next">Check back tomorrow for another fun finance fact of the day.</p>
      </div>
    </div>
  );
}
