/*
 * TermsOfService.tsx
 * Terms of Service page for StockSense.
 */
import React from "react";
import { Link } from "react-router-dom";
import "./legal.css";

const TermsOfService: React.FC = () => {
  return (
    <div className="legal-container">
      <div className="legal-card">
        <div className="legal-header">
          <div className="legal-branding">
            <Link to="/" className="legal-brand-name">
              Stock<span className="legal-brand-highlight">Sense</span>
            </Link>
          </div>
          <h1 className="legal-title">Terms of Service</h1>
          <p className="legal-effective">Effective Date: April 1, 2025</p>
        </div>

        <div className="legal-body">
          <p className="legal-intro">
            Welcome to StockSense. By creating an account or using our platform,
            you agree to the following terms. Please read them carefully.
          </p>

          <section className="legal-section">
            <h2>1. About StockSense</h2>
            <p>
              StockSense is an AI-powered stock sentiment and portfolio tracking
              platform developed as a University of South Carolina capstone
              project. It is intended for informational and educational purposes
              only.
            </p>
          </section>

          <section className="legal-section">
            <h2>2. Not Financial Advice</h2>
            <p>
              Nothing on StockSense constitutes financial, investment, legal, or
              tax advice. All content — including sentiment scores, AI-generated
              summaries, portfolio analytics, and news aggregations — is provided
              for informational purposes only. You should not make investment
              decisions based solely on information provided by StockSense.
              Always consult a qualified financial professional before making
              investment decisions.
            </p>
          </section>

          <section className="legal-section">
            <h2>3. Eligibility</h2>
            <p>
              You must be at least 18 years old to use StockSense. By creating
              an account, you represent and warrant that you meet this age
              requirement.
            </p>
          </section>

          <section className="legal-section">
            <h2>4. Your Account</h2>
            <p>
              You are responsible for maintaining the confidentiality of your
              account credentials and for all activity that occurs under your
              account. You agree to notify us immediately of any unauthorized
              use. We reserve the right to suspend or terminate accounts that
              violate these terms.
            </p>
          </section>

          <section className="legal-section">
            <h2>5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the platform for any unlawful purpose</li>
              <li>Attempt to reverse-engineer or scrape the platform</li>
              <li>Submit false or misleading information during registration</li>
              <li>
                Use StockSense to manipulate financial markets or engage in
                market abuse
              </li>
              <li>
                Interfere with the security or integrity of the platform
              </li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>6. Data Accuracy and Limitations</h2>
            <p>
              Due to API rate limits and project budget constraints, StockSense
              currently covers approximately 40 supported stock tickers. News
              article counts are intentionally limited per source. Sentiment
              scores are generated by automated AI models and may not accurately
              reflect real-world market conditions. We make no guarantees
              regarding the accuracy, completeness, or timeliness of any data
              displayed on the platform.
            </p>
          </section>

          <section className="legal-section">
            <h2>7. Intellectual Property</h2>
            <p>
              All content, design, and code on StockSense are the property of
              the AI Roosters development team. You may not copy, reproduce, or
              distribute any part of the platform without prior written
              permission.
            </p>
          </section>

          <section className="legal-section">
            <h2>8. Disclaimer of Warranties</h2>
            <p>
              StockSense is provided "as is" without warranties of any kind,
              either express or implied. We do not warrant that the platform
              will be uninterrupted, error-free, or free of harmful components.
            </p>
          </section>

          <section className="legal-section">
            <h2>9. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, the StockSense team shall
              not be liable for any indirect, incidental, special, or
              consequential damages arising from your use of or inability to use
              the platform, including any financial losses resulting from
              reliance on information provided by StockSense.
            </p>
          </section>

          <section className="legal-section">
            <h2>10. Changes to These Terms</h2>
            <p>
              We may update these Terms of Service from time to time. Continued
              use of the platform after any changes constitutes your acceptance
              of the new terms.
            </p>
          </section>

          <section className="legal-section">
            <h2>11. Contact</h2>
            <p>
              If you have any questions about these terms, please reach out
              through our GitHub repository at{" "}
              <a
                href="https://github.com/SCCapstone/ai_roosters"
                target="_blank"
                rel="noopener noreferrer"
              >
                github.com/SCCapstone/ai_roosters
              </a>
              .
            </p>
          </section>
        </div>

        <div className="legal-footer">
          <Link to="/privacy" className="legal-link">
            Privacy Policy
          </Link>
          <span className="legal-divider">·</span>
          <Link to="/register" className="legal-link">
            Back to Sign Up
          </Link>
          <span className="legal-divider">·</span>
          <Link to="/" className="legal-link">
            Home
          </Link>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
