export const TICKER_NAMES: Record<string, string> = {
  KSS:   "Kohl's Corporation",
  ALK:   "Alaska Air Group",
  NVS:   "Novartis AG",
  AXP:   "American Express",
  FCX:   "Freeport-McMoRan",
  CSX:   "CSX Corporation",
  DAL:   "Delta Air Lines",
  NTAP:  "NetApp",
  MRK:   "Merck & Co.",
  COP:   "ConocoPhillips",
  BHP:   "BHP Group",
  EA:    "Electronic Arts",
  TSLA:  "Tesla, Inc.",
  NVDA:  "NVIDIA Corporation",
  AAPL:  "Apple Inc.",
  MSFT:  "Microsoft Corporation",
  AMZN:  "Amazon.com",
  AMD:   "Advanced Micro Devices",
  META:  "Meta Platforms, Inc.",
  GOOGL: "Alphabet Inc. (Class A)",
  GOOG:  "Alphabet Inc. (Class C)",
  PLTR:  "Palantir Technologies",
  MU:    "Micron Technology",
  NFLX:  "Netflix, Inc.",
  NKE:   "Nike, Inc.",
  AAL:   "American Airlines Group",
  BAC:   "Bank of America Corp.",
  F:     "Ford Motor Company",
  INTC:  "Intel Corporation",
  XOM:   "Exxon Mobil Corporation",
  T:     "AT&T Inc.",
  SOFI:  "SoFi Technologies",
  PLUG:  "Plug Power Inc.",
  MARA:  "Marathon Digital Holdings",
  SNAP:  "Snap Inc.",
  COIN:  "Coinbase Global",
  AMC:   "AMC Entertainment Holdings",
  RIVN:  "Rivian Automotive",
  CCL:   "Carnival Corporation",
  ENPH:  "Enphase Energy",
};

export const ALL_TICKERS = Object.keys(TICKER_NAMES);